export const fonts = {
	dmSansBlack: 'DMSans-Black',
	dmSansBlackItalic: 'DMSans-BlackItalic',
	dmSansBold: 'DMSans-Bold',
	dmSansBoldItalic: 'DMSans-BoldItalic',
	dmSansExtraBold: 'DMSans-ExtraBold',
	dmSansExtraBoldItalic: 'DMSans-ExtraBoldItalic',
	dmSansExtraLight: 'DMSans-ExtraLight',
	dmSansExtraLightItalic: 'DMSans-ExtraLightItalic',
	dmSansItalic: 'DMSans-Italic',
	dmSansLight: 'DMSans-Light',
	dmSansLightItalic: 'DMSans-LightItalic',
	dmSansMedium: 'DMSans-Medium',
	dmSansMediumItalic: 'DMSans-MediumItalic',
	dmSansRegular: 'DMSans-Regular',
	dmSansSemiBold: 'DMSans-SemiBold',
	dmSansSemiBoldItalic: 'DMSans-SemiBoldItalic',
	dmSansThin: 'DMSans-Thin',
	dmSansThinItalic: 'DMSans-ThinItalic',
	golosTextBlack: 'GolosText-Black',
	golosTextBold: 'GolosText-Bold',
	golosTextExtraBold: 'GolosText-ExtraBold',
	golosTextMedium: 'GolosText-Medium',
	golosTextRegular: 'GolosText-Regular',
	golosTextSemiBold: 'GolosText-SemiBold',
};
